--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alvin0319/PlayerTrade
build-by-default: true
branches:
- pm4
- pm5
projects:
  PlayerTrade:
    path: ""
    libs:
      - src: Muqsit/InvMenu/InvMenu
        branch: "4.0"
        version: ^4.4.0
...
