name: PlayerTrade
authors: [alvin0319, cosmicnebula200, AGTHARN]
main: alvin0319\PlayerTrade\PlayerTrade
version: 2.0.1
api: 4.0.0

permissions:
  playertrade.command:
    description: Allows player to use /trade command
    default: true
